apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: production
  labels:
    app: payment-service
    component: backend
    compliance: pci
data:
  # Database configuration
  database.host: "postgres-primary.production.svc.cluster.local"
  database.port: "5432"
  database.name: "payments_db"
  database.pool.size: "20"
  database.pool.timeout: "30s"
  database.ssl_mode: "require"
  
  # Kafka configuration
  kafka.brokers: "kafka-0.kafka-headless.production.svc.cluster.local:9092,kafka-1.kafka-headless.production.svc.cluster.local:9092,kafka-2.kafka-headless.production.svc.cluster.local:9092"
  kafka.topic.payments: "payment-events"
  kafka.topic.payment_status: "payment-status-updates"
  kafka.topic.audit: "payment-audit-log"
  kafka.consumer.group: "payment-service-consumer"
  kafka.producer.retries: "5"
  kafka.producer.idempotent: "true"
  
  # Service configuration
  service.port: "8004"
  service.metrics.port: "9090"
  service.timeout.read: "30s"
  service.timeout.write: "30s"
  service.timeout.idle: "60s"
  service.tls.enabled: "true"
  
  # Payment processing
  payment.max_retry_attempts: "3"
  payment.timeout: "30s"
  payment.currency: "USD"
  payment.min_amount: "0.01"
  payment.max_amount: "999999.99"
  
  # Security configuration
  security.encryption_algorithm: "AES256"
  security.token_expiry: "300s"  # 5 minutes
  security.audit_enabled: "true"
  security.pci_compliance_mode: "true"
  
  # Rate limiting
  ratelimit.enabled: "true"
  ratelimit.requests_per_minute: "100"
  ratelimit.burst: "150"
  
  # Application configuration
  app.config.yaml: |
    server:
      port: 8004
      host: 0.0.0.0
      graceful_shutdown_timeout: 60s
      tls:
        enabled: true
        cert_file: /etc/tls/tls.crt
        key_file: /etc/tls/tls.key
        min_version: "1.2"
    
    security:
      enable_audit_log: true
      enable_request_encryption: true
      enable_response_encryption: true
      session_timeout: 300
    
    compliance:
      pci_dss: true
      log_retention_days: 365
      data_retention_days: 2555  # 7 years
    
    logging:
      level: info
      format: json
      output: stdout
      sensitive_data_masking: true
    
    tracing:
      enabled: true
      service_name: payment-service
      endpoint: http://tempo.monitoring.svc.cluster.local:4317
      sample_rate: 1.0  # 100% for payment tracing
    
    metrics:
      enabled: true
      port: 9090
      path: /metrics