apiVersion: v2
name: enterprise-system
description: A Helm chart for the Enterprise System microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - enterprise
  - microservices
  - kubernetes
home: https://github.com/enterprise/enterprise-system
sources:
  - https://github.com/enterprise/enterprise-system
maintainers:
  - name: Platform Team
    email: platform@enterprise.com
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: kafka
    version: "25.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
  - name: kong
    version: "2.x.x"
    repository: "https://charts.konghq.com"
    condition: kong.enabled
  - name: prometheus
    version: "23.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.x.x"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled