# Development environment values
global:
  environment: development
  domain: dev.enterprise.com
  
services:
  userService:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    autoscaling:
      enabled: false
      
  orderService:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    autoscaling:
      enabled: false
      
  productService:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    autoscaling:
      enabled: false
      
  paymentService:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    autoscaling:
      enabled: false
    pciCompliance: false  # Relaxed for dev
    
postgresql:
  primary:
    persistence:
      size: 10Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
  readReplicas:
    replicaCount: 0  # No replicas in dev
    
redis:
  master:
    persistence:
      size: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  replica:
    replicaCount: 0  # No replicas in dev
  sentinel:
    enabled: false
    
kafka:
  replicaCount: 1
  persistence:
    size: 10Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  zookeeper:
    replicaCount: 1
    persistence:
      size: 1Gi
      
kong:
  proxy:
    type: NodePort
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
      
monitoring:
  prometheus:
    retention: 7d
    storageSize: 10Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
  grafana:
    persistence:
      size: 1Gi
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
        
ingress:
  hosts:
    - host: api.dev.enterprise.com
      paths:
        - path: /api/v1/users
          pathType: Prefix
          service: user-service
        - path: /api/v1/orders
          pathType: Prefix
          service: order-service
        - path: /api/v1/products
          pathType: Prefix
          service: product-service
        - path: /api/v1/payments
          pathType: Prefix
          service: payment-service
  tls:
    - secretName: api-dev-tls
      hosts:
        - api.dev.enterprise.com
        
networkPolicies:
  enabled: false  # Disabled for easier debugging
  
resourceQuotas:
  enabled: true
  requests:
    cpu: "100"
    memory: "200Gi"
  limits:
    cpu: "200"
    memory: "400Gi"
    
nodeSelector: {}  # Any node in dev

affinity: {}  # No affinity rules in dev