# Resource Quotas for each namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: development-quota
  namespace: development
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    limits.cpu: "200"
    limits.memory: "400Gi"
    persistentvolumeclaims: "20"
    services.loadbalancers: "2"
    services.nodeports: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: staging
spec:
  hard:
    requests.cpu: "500"
    requests.memory: "1000Gi"
    limits.cpu: "1000"
    limits.memory: "2000Gi"
    persistentvolumeclaims: "50"
    services.loadbalancers: "5"
    services.nodeports: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: production
spec:
  hard:
    requests.cpu: "2000"
    requests.memory: "4000Gi"
    limits.cpu: "4000"
    limits.memory: "8000Gi"
    persistentvolumeclaims: "100"
    services.loadbalancers: "10"
    services.nodeports: "0"  # No NodePorts in production
---
# Limit Ranges
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: development
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "50m"
      memory: "128Mi"
    min:
      cpu: "10m"
      memory: "64Mi"
    max:
      cpu: "2000m"
      memory: "4Gi"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: staging
spec:
  limits:
  - default:
      cpu: "1000m"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    min:
      cpu: "50m"
      memory: "128Mi"
    max:
      cpu: "4000m"
      memory: "8Gi"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: production
spec:
  limits:
  - default:
      cpu: "2000m"
      memory: "4Gi"
    defaultRequest:
      cpu: "200m"
      memory: "512Mi"
    min:
      cpu: "100m"
      memory: "256Mi"
    max:
      cpu: "8000m"
      memory: "16Gi"
    type: Container