# Storage Classes for Enterprise System
---
# GP3 Encrypted Storage Class (Default)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-encrypted
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
  iops: "3000"
  throughput: "125"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
# High IOPS Storage Class for Databases
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-high-iops
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
  iops: "10000"
  throughput: "500"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
# Provisioned IOPS Storage Class for Critical Workloads
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: io2-high-performance
provisioner: ebs.csi.aws.com
parameters:
  type: io2
  fsType: ext4
  encrypted: "true"
  iops: "20000"
reclaimPolicy: Retain  # Retain for critical data
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
# Cold Storage Class for Backups
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc1-cold-storage
provisioner: ebs.csi.aws.com
parameters:
  type: sc1
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
# EFS Storage Class for Shared Storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-shared
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-xxxxxxxx  # Replace with actual EFS ID
  directoryPerms: "700"
reclaimPolicy: Retain
allowVolumeExpansion: false
volumeBindingMode: Immediate