apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: production
  labels:
    app: product-service
    component: backend
    tier: api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
  - name: http
    port: 8003
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service
  namespace: production
  labels:
    app: product-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/product-service-role